apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and Deploy to GKE

on:
  push:
    branches:
      - 'main'


env:
  PROJECT_ID: ps-ssingh-gcp
  GKE_CLUSTER: saas-cluster # Add your cluster name here.
  GKE_ZONE: us-east1-b  # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: static-site

jobs:
  setup-gcloud:
    environment: gcp-dev

    steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1

    - name: Setup gcloud CLI
      uses: docker://google/cloud-sdk
      shell: bash
      run: |
        set -x
        gcloud config set project ${{ env.PROJECT_ID }}

        #Activate Service Account
        echo "${{ secrets.GCP_AUTH }}" | base64 --decode > gcp-credentials.json        
        gcloud auth activate-service-account --key-file="gcp-credentials.json"

  configure-gke:
    environment: gcp-dev
    needs: setup-gcloud 
    steps:
      - name: Configure GKE credentials
        uses: docker://google/cloud-sdk
        shell: bash
        run: |
          set -x
          gcloud config set project ${{ env.PROJECT_ID }}

          #Activate Service Account
          echo "${{ secrets.GCP_AUTH }}" | base64 --decode > gcp-credentials.json        
          gcloud auth activate-service-account --key-file="gcp-credentials.json"

          gcloud --quiet auth configure-docker

          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone=${{ env.GKE_ZONE }} --project=${{ env.PROJECT_ID }}


